# Generated by Django 6.0.3 on 2026-04-16 10:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_alter_book_pages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='published_date',
            field=models.DateField(default=datetime.date(2025, 4, 1)),
            preserve_default=False,
        ),
    ]
