# Generated by Django 6.0.3 on 2026-04-16 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_alter_book_published_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='language',
            field=models.CharField(default='English', max_length=50),
            preserve_default=False,
        ),
    ]
