# Generated by Django 6.0.3 on 2026-04-25 07:43

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0009_rating_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cover',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='book',
            name='pdf_file',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='file'),
        ),
    ]
