# Generated by Django 6.0.3 on 2026-04-23 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(blank=True, choices=[('admin', 'Admin'), ('fiction_employee', 'Fiction Employee'), ('nonfiction_employee', 'Non-Fiction Employee')], max_length=30, null=True),
        ),
    ]
