# Generated by Django 6.0.3 on 2026-04-24 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(blank=True, choices=[('fiction_employee', 'Fiction Employee'), ('nonfiction_employee', 'Non-Fiction Employee')], max_length=30, null=True),
        ),
    ]
